### PR TITLE
feat!: better defaults for copy_directories + only add existing ones

### PR DESCRIPTION
**Pull request by mrcjkb**
BREAKING CHANGE: This could result in new directories being added to packages that did not set the copy_directories input.

### CODE REVIEW

**Comment by mrcjkb** [comment]
I've noticed that `:help runtimepath` does not include some common plugin directories like `autoload`, `queries`, ...

Since adding new defaults is technically a breaking change, we should probably as for feedback on which directories to add in some Neovim groups.

**Comment by teto** [comment]
my experience with CI is that the more code you move to the script and the less you expose in the CI-only part is better. It makes troubleshooting easier.  In the long run, I think it's better to implement the default directly in [luarocks-tag-release.lua](https://github.com/nvim-neorocks/luarocks-tag-release/blob/master/bin/luarocks-tag-release.lua). 

As you mentioned you wanted the action to remain generic, maybe instead we could have an input: "neovimplugin" (autodetected according to label even) that would change some settings: 
- add "neovim" label
- add these folders to copy_directories

**Comment by mrcjkb** [comment]
> my experience with CI is that the more code you move to the script and the less you expose in the CI-only part is better. It makes troubleshooting easier. In the long run, I think it's better to implement the default directly in [luarocks-tag-release.lua](https://github.com/nvim-neorocks/luarocks-tag-release/blob/master/bin/luarocks-tag-release.lua).
> 
> As you mentioned you wanted the action to remain generic, maybe instead we could have an input: "neovimplugin" (autodetected according to label even) that would change some settings:
> 
>     * add "neovim" label
> 
>     * add these folders to copy_directories

I see your point about troubleshooting.
But I'm not sure how I feel about a separate input or logic that causes directories to be added on top of the `copy_directories` input based on some condition. That sounds to me like it could increase complexity (both internally and from a UX viewpoint). I might be wrong though...

Another option would be to add the default plugin directories if the `copy_directories` input has the value `{{ neovim.plugin.dirs }}` (which we could set by default).

I'll put some more thought into it in the next few days.

**Comment by mrcjkb** [comment]
I have updated this with the `{{ neovim.plugin.dirs }}` approach.

**Pull request merged**
